namespace ModularForge.Trailback.Editor
{
    /// <summary>
    /// Defines the severity level of a validation message generated by the Trailback setup validator.
    /// </summary>
    public enum ValidationSeverity
    {
        /// <summary>
        /// Informational message.
        /// Indicates a successful check or useful diagnostic that does not require user action.
        /// </summary>
        Info = 0,
        
        /// <summary>
        /// Warning message.
        /// Indicates a potential issue or configuration that should be reviewed but does not prevent Trailback
        /// from functioning.
        /// </summary>
        Warning = 1,
        
        /// <summary>
        /// Error message.
        /// Indicates a critical setup problem that may prevent Trailback from functioning correctly and should be
        /// resolved before use.
        /// </summary>
        Error = 2,
    }
}