using UnityEngine;

namespace ModularForge.Trailback.Editor
{
    /// <summary>
    /// Represents a single validation message generated by the Trailback setup validator.
    /// </summary>
    public readonly struct ValidationMessage
    {
        /// <summary>
        /// Severity level of the validation message.
        /// </summary>
        public readonly ValidationSeverity Severity;

        /// <summary>
        /// Describes the validation result that was produced, such as a missing component, duplicate setup,
        /// or configuration warning.
        /// </summary>
        public readonly string Message;


        /// <summary>
        /// Optional Unity object associated with the message. Used to provide clickable context in the Console.
        /// </summary>
        public readonly Object Context;


        /// <summary>
        /// Creates a new validation message.
        /// </summary>
        /// <param name="severity">
        /// Severity level of the validation message.
        /// </param>
        /// <param name="message">
        /// Human-readable validation message.
        /// </param>
        /// <param name="context">
        /// Optional Unity object associated with the message.
        /// </param>
        public ValidationMessage(ValidationSeverity severity, string message, Object context = null)
        {
            Severity = severity;
            Message = message;
            Context = context;
        }
    }
}