namespace ModularForge.Trailback.Core
{
    /// <summary>
    /// Represents an immutable snapshot of Trailback's  current runtime state.
    /// </summary>
    /// <remarks>
    /// This immutable snapshot captures Trailback's complete diagnostic state at the
    /// time it is created.
    ///
    /// It aggregates navigation, history, and runtime statistics into a single value,
    /// providing a consistent view of Trailback's state for diagnostics, runtime
    /// monitoring, debugging, and developer tooling.
    ///
    /// Instances are generated by <see cref="BackResolver"/> and do not reflect
    /// subsequent changes made to the underlying navigation system.
    /// </remarks>
    public readonly struct TrailbackState
    {
        /// <summary>
        /// Total number of active navigation categories currently tracked by Trailback.
        /// </summary>
        public int ActiveCategoryCount { get; }

        /// <summary>
        /// Total number of navigation entries currently stored in history.
        /// </summary>
        public int TotalHistoryEntries { get; }

        /// <summary>
        /// Name of the highest priority navigation category.
        /// </summary>
        public string HighestPriorityCategory { get; }

        /// <summary>
        /// Current navigation state snapshot.
        /// </summary>
        public TrailbackNavigationSnapshot NavigationSnapshot { get; }

        /// <summary>
        /// Current navigation history snapshot.
        /// </summary>
        public TrailbackHistorySnapshot HistorySnapshot { get; }
        
        /// <summary>
        /// Creates a new Trailback runtime state snapshot.
        /// </summary>
        /// <param name="navigationSnapshot">
        /// Current navigation state snapshot.
        /// </param>
        /// <param name="historySnapshot">
        /// Current navigation history snapshot.
        /// </param>
        /// <param name="activeCategoryCount">
        /// Number of active navigation categories.
        /// </param>
        /// <param name="totalHistoryEntries">
        /// Total number of navigation entries currently stored in history.
        /// </param>
        /// <param name="highestPriorityCategory">
        /// Name of the highest priority navigation category.
        /// </param>
        public TrailbackState(
            TrailbackNavigationSnapshot navigationSnapshot,
            TrailbackHistorySnapshot historySnapshot,
            int activeCategoryCount,
            int totalHistoryEntries,
            string highestPriorityCategory
        )
        {
            ActiveCategoryCount = activeCategoryCount;
            TotalHistoryEntries = totalHistoryEntries;
            HighestPriorityCategory = highestPriorityCategory;

            NavigationSnapshot = navigationSnapshot;
            HistorySnapshot = historySnapshot;
        }
    }
}