using ModularForge.Trailback.Diagnostics;

namespace ModularForge.Trailback.Core
{
    /// <summary>
    /// Represents an immutable snapshot of Trailback's  current runtime state.
    /// </summary>
    /// <remarks>
    /// TrailbackState is primarily intended for diagnostics, monitoring, debugging, and
    /// developer tooling.
    ///
    /// Instances are generated by BackResolver and exposed through Trailback's state APIs.
    ///
    /// TrailbackState is immutable and represents a snapshot of Trailback's runtime state at
    /// the time it was created.
    /// </remarks>
    public readonly struct TrailbackState
    {
        /// <summary>
        /// Name of the currently active navigation entry.
        /// </summary>
        public string Current { get; }
        
        /// <summary>
        /// Name of the navigation entry that would become active after a successful back navigation.
        /// </summary>
        public string Previous{ get; }

        /// <summary>
        /// Indicates whether a back navigation request can currently be executed.
        /// </summary>
        public bool CanGoBack{ get; }

        /// <summary>
        /// Total number of active navigation categories currently tracked by Trailback.
        /// </summary>
        public int ActiveCategoryCount{ get; }

        /// <summary>
        /// Total number of navigation entries currently stored in history.
        /// </summary>
        public int TotalHistoryEntries{ get; }

        /// <summary>
        /// Name of the category that currently has the highest navigation priority.
        /// </summary>
        public string HighestPriorityCategory{ get; }
        
        /// <summary>
        /// Indicates why navigation is currently blocked.
        /// </summary>
        public BackBlockReason BlockReason{ get; }

        public string BlockDetails{ get; }

        /// <summary>
        /// Creates a new Trailback runtime state snapshot.
        /// </summary>
        /// <param name="current">
        /// Name of the currently active navigation entry.
        /// </param>
        /// <param name="previous">
        /// Name of the previous navigation entry.
        /// </param>
        /// <param name="canGoBack">
        /// Indicates whether back navigation can currently be executed.
        /// </param>
        /// <param name="activeCategoryCount">
        /// Number of active navigation categories.
        /// </param>
        /// <param name="totalHistoryEntries">
        /// Total number of entries currently stored in history.
        /// </param>
        /// <param name="highestPriorityCategory">
        /// Name of the highest priority category.
        /// </param>
        /// <param name="blockReason">
        /// Reason why navigation is currently blocked.
        /// </param>
        /// <param name="blockDetails">
        /// Additional information describing the block reason.
        /// </param>
        public TrailbackState(
            string current, 
            string previous, 
            bool canGoBack, 
            int activeCategoryCount, 
            int totalHistoryEntries, 
            string highestPriorityCategory, 
            BackBlockReason blockReason, 
            string backDetails)
        {
            Current = current;
            Previous = previous;
            CanGoBack = canGoBack;
            ActiveCategoryCount = activeCategoryCount;
            TotalHistoryEntries = totalHistoryEntries;
            HighestPriorityCategory = highestPriorityCategory;
            BlockReason = blockReason;
            BlockDetails = backDetails;
        }
    }
}